version: "3"

services:
  SeaChartCreator:
    image: sea-chart-creator:1.0
    build: ./docker
    hostname: scc
    volumes:
      - ./:/SeaChartCreator/

    command: run
    restart: unless-stopped
