version: "3"

services:
  SeaChartCreator:
    image: sea-chart-creator:1.0
    build: ./docker
    hostname: scc
    volumes:
      - ./:/SeaChartCreator/
      - ./etc/ImageMagick-6/policy.xml:/etc/ImageMagick-6/policy.xml
    command: run
    restart: unless-stopped
